Add initial console app
salemove/console-app pull request #1
Opened 2017-09-20 15:44 UTC by indrekj

![screen shot 2017-09-20 at 17 47 08](https://user-images.githubusercontent.com/3438/30653399-a63c0e90-9e33-11e7-9526-822e7f230479.png)

2017-09-20 15:53 UTC, deiwin commented
Nice! 💻

2017-09-20 17:56 UTC, willmore commented on app/app.rb
> +    @server      = @prompt.select('SaleMove API location?', API_LOCATIONS)
Feature request: read from optional ~/.salemove.yaml

2017-09-20 17:57 UTC, willmore commented on app/app.rb
> +    info ">> Creating a reactive engagement request"
`">> Requesting engagement..."`

2017-09-20 17:57 UTC, urmastalimaa commented on app/gui/keymaps/_global_.rb
> +  key(:ctrl_c) { Vedeu.exit }
Can you document the key bindings in README?

2017-09-20 17:59 UTC, willmore requested changes
Please add MIT license.

2017-09-21 07:18 UTC, indrekj commented
@willmore updated

2017-09-21 07:40 UTC, willmore approved these changes

2017-09-21 07:41 UTC, urmastalimaa approved these changes

2017-09-21 07:44 UTC, indrekj commented
!merge

2017-09-21 07:44 UTC, merged